/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.wagnerpassos.visao;

import br.wagnerpassos.modelo.dao.LoginDAO;
import br.wagnerpassos.swing.util.ImpressoraSwing;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author wagne
 */
public class TelaLogin extends javax.swing.JDialog {

    /**
     * Creates new form TelaLogin2
     */
    public TelaLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getRootPane().setDefaultButton(botaoAcessar);
    }
    
    public void fechar(){
        System.exit(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lTitulo = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        separadorUsuario = new javax.swing.JSeparator();
        lUsuario = new javax.swing.JLabel();
        separadorSenha = new javax.swing.JSeparator();
        lSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        botaoAcessar = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        lX = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(48, 56, 157));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/yugiohpng.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 360, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-71, 0, 440, 510));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lTitulo.setBackground(new java.awt.Color(80, 86, 170));
        lTitulo.setFont(new java.awt.Font("ChronicaPro-Regular", 0, 48)); // NOI18N
        lTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lTitulo.setText("   Painel de Login");
        lTitulo.setOpaque(true);
        jPanel2.add(lTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 420, 130));

        txtUsuario.setFont(new java.awt.Font("ChronicaProMediumIt", 0, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(48, 56, 157));
        txtUsuario.setToolTipText("");
        txtUsuario.setBorder(null);
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        jPanel2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 340, 20));

        separadorUsuario.setForeground(new java.awt.Color(48, 56, 157));
        jPanel2.add(separadorUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 340, 10));

        lUsuario.setFont(new java.awt.Font("ChronicaProMediumIt", 0, 18)); // NOI18N
        lUsuario.setForeground(new java.awt.Color(48, 56, 157));
        lUsuario.setText("Usuário");
        jPanel2.add(lUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 70, 20));

        separadorSenha.setForeground(new java.awt.Color(48, 56, 157));
        jPanel2.add(separadorSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 340, 10));

        lSenha.setFont(new java.awt.Font("ChronicaProMediumIt", 0, 18)); // NOI18N
        lSenha.setForeground(new java.awt.Color(48, 56, 157));
        lSenha.setText("Senha");
        jPanel2.add(lSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 70, 20));

        txtSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSenha.setForeground(new java.awt.Color(48, 56, 157));
        txtSenha.setBorder(null);
        txtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSenhaFocusLost(evt);
            }
        });
        jPanel2.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 340, 20));

        botaoAcessar.setBackground(new java.awt.Color(80, 86, 170));
        botaoAcessar.setFont(new java.awt.Font("ChronicaPro-Regular", 0, 18)); // NOI18N
        botaoAcessar.setForeground(new java.awt.Color(255, 255, 255));
        botaoAcessar.setText("Acessar");
        botaoAcessar.setBorder(null);
        botaoAcessar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                botaoAcessarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                botaoAcessarFocusLost(evt);
            }
        });
        botaoAcessar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoAcessarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoAcessarMouseExited(evt);
            }
        });
        botaoAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAcessarActionPerformed(evt);
            }
        });
        jPanel2.add(botaoAcessar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 340, 30));

        botaoSair.setBackground(new java.awt.Color(80, 86, 170));
        botaoSair.setFont(new java.awt.Font("ChronicaPro-Regular", 0, 18)); // NOI18N
        botaoSair.setForeground(new java.awt.Color(255, 255, 255));
        botaoSair.setText("Sair");
        botaoSair.setBorder(null);
        botaoSair.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                botaoSairFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                botaoSairFocusLost(evt);
            }
        });
        botaoSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoSairMouseExited(evt);
            }
        });
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });
        jPanel2.add(botaoSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 340, 30));

        lX.setFont(new java.awt.Font("ChronicaProMediumIt", 0, 18)); // NOI18N
        lX.setForeground(new java.awt.Color(48, 56, 157));
        lX.setText("X");
        lX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lXMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lXMouseExited(evt);
            }
        });
        jPanel2.add(lX, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 20, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 0, 420, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        fechar();
    }//GEN-LAST:event_botaoSairActionPerformed

    private void lXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lXMouseClicked
        fechar();
    }//GEN-LAST:event_lXMouseClicked

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        lUsuario.setForeground(new Color(210, 110, 30));
        separadorUsuario.setForeground(new Color(210, 110, 30));
    }//GEN-LAST:event_txtUsuarioFocusGained

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        lUsuario.setForeground(new Color(48,56,157));
        separadorUsuario.setForeground(new Color(48,56,157));
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void txtSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusGained
        lSenha.setForeground(new Color(210, 110, 30));
        separadorSenha.setForeground(new Color(210, 110, 30));
    }//GEN-LAST:event_txtSenhaFocusGained

    private void txtSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusLost
        lSenha.setForeground(new Color(48,56,157));
        separadorSenha.setForeground(new Color(48,56,157));
    }//GEN-LAST:event_txtSenhaFocusLost

    private void botaoAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAcessarActionPerformed
        LoginDAO loginDAO = new LoginDAO();
        String usuario = txtUsuario.getText();
        String senha = new String(txtSenha.getPassword());
        
        if(loginDAO.realizarLogin(usuario, senha) != null){
            ImpressoraSwing.getInstance().impressoraJOP("Seja bem vindo ao SISTEMA!");
            dispose();
        }else
            ImpressoraSwing.getInstance().impressoraJOP("Credênciais de login inválidas!");
    }//GEN-LAST:event_botaoAcessarActionPerformed

    private void lXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lXMouseEntered
        lX.setForeground(new Color(210, 110, 30));
    }//GEN-LAST:event_lXMouseEntered

    private void lXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lXMouseExited
        lX.setForeground(new Color(48,56,157));
    }//GEN-LAST:event_lXMouseExited

    private void botaoAcessarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAcessarMouseEntered
        botaoAcessar.setBackground(new Color(210, 110, 30));
    }//GEN-LAST:event_botaoAcessarMouseEntered

    private void botaoSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSairMouseEntered
        botaoSair.setBackground(new Color(210, 110, 30));
    }//GEN-LAST:event_botaoSairMouseEntered

    private void botaoAcessarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAcessarMouseExited
        botaoAcessar.setBackground(new Color(80, 86, 170));
    }//GEN-LAST:event_botaoAcessarMouseExited

    private void botaoSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSairMouseExited
       botaoSair.setBackground(new Color(80, 86, 170));
    }//GEN-LAST:event_botaoSairMouseExited

    private void botaoAcessarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_botaoAcessarFocusGained
        botaoAcessar.setBackground(new Color(210, 110, 30));
    }//GEN-LAST:event_botaoAcessarFocusGained

    private void botaoAcessarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_botaoAcessarFocusLost
        botaoAcessar.setBackground(new Color(80, 86, 170));
    }//GEN-LAST:event_botaoAcessarFocusLost

    private void botaoSairFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_botaoSairFocusGained
        botaoSair.setBackground(new Color(210, 110, 30));
    }//GEN-LAST:event_botaoSairFocusGained

    private void botaoSairFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_botaoSairFocusLost
        botaoSair.setBackground(new Color(80, 86, 170));
    }//GEN-LAST:event_botaoSairFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaLogin dialog = new TelaLogin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public static class DialogDragListener extends MouseAdapter {

        private final JDialog dialog;
        private Point mouseDownCompCoords = null;

        public DialogDragListener(JDialog dialog) {
            this.dialog = dialog;
        }

        public void mouseReleased(MouseEvent e) {
            mouseDownCompCoords = null;
        }

        public void mousePressed(MouseEvent e) {
            mouseDownCompCoords = e.getPoint();
        }

        public void mouseDragged(MouseEvent e) {
            Point currCoords = e.getLocationOnScreen();
            dialog.setLocation(currCoords.x - mouseDownCompCoords.x, currCoords.y - mouseDownCompCoords.y);
        }
    }
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAcessar;
    private javax.swing.JButton botaoSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lSenha;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JLabel lUsuario;
    private javax.swing.JLabel lX;
    private javax.swing.JSeparator separadorSenha;
    private javax.swing.JSeparator separadorUsuario;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
