/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.wagnerpassos.view;

import br.wagnerpassos.fabrica.ConnectionFactory;
import javax.swing.JDialog;

/**
 *
 * @author wagne
 */
public class FormularioPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormularioPrincipal
     */
    public FormularioPrincipal() {
        initComponents();
        //telaLogin();
    }
    
    public void telaLogin(){
        FormularioLogin formulario = new FormularioLogin(this, true);
        formulario.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        formulario.setLocationRelativeTo(null);
        formulario.setResizable(false);
        formulario.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelGeral = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        botaoTorneio = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        botaoPrincipal = new javax.swing.JMenu();
        botaoCadastro = new javax.swing.JMenu();
        menuJogador = new javax.swing.JMenuItem();
        menuTorneio = new javax.swing.JMenuItem();
        botaoRelatorio = new javax.swing.JMenu();
        botaoAjuda = new javax.swing.JMenu();
        menuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema - NOMEDALOJA");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Torneio"));

        botaoTorneio.setText("Iniciar novo Torneio");
        botaoTorneio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTorneioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoTorneio, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(660, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoTorneio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelGeralLayout = new javax.swing.GroupLayout(painelGeral);
        painelGeral.setLayout(painelGeralLayout);
        painelGeralLayout.setHorizontalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelGeralLayout.setVerticalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGeralLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 314, Short.MAX_VALUE))
        );

        botaoPrincipal.setText("Principal");
        botaoPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuBar1.add(botaoPrincipal);

        botaoCadastro.setText("Cadastro");
        botaoCadastro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        menuJogador.setBackground(new java.awt.Color(255, 255, 255));
        menuJogador.setText("Jogador");
        menuJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuJogadorActionPerformed(evt);
            }
        });
        botaoCadastro.add(menuJogador);

        menuTorneio.setText("Torneio");
        menuTorneio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTorneioActionPerformed(evt);
            }
        });
        botaoCadastro.add(menuTorneio);

        jMenuBar1.add(botaoCadastro);

        botaoRelatorio.setText("Relatório");
        botaoRelatorio.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuBar1.add(botaoRelatorio);

        botaoAjuda.setText("Ajuda");
        botaoAjuda.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        menuSobre.setText("Sobre");
        botaoAjuda.add(menuSobre);

        jMenuBar1.add(botaoAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuJogadorActionPerformed
        FormularioJogador formulario = new FormularioJogador(this, true);
        formulario.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        formulario.setTitle("Manutenção de Jogadores");
        formulario.setLocationRelativeTo(null);
        formulario.setResizable(false);
        formulario.setVisible(true);
    }//GEN-LAST:event_menuJogadorActionPerformed

    private void menuTorneioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTorneioActionPerformed
        FormularioTorneio formulario = new FormularioTorneio(this, true);
        formulario.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        formulario.setTitle("Manutenção de Torneios");
        formulario.setLocationRelativeTo(null);
        formulario.setResizable(false);
        formulario.setVisible(true);
    }//GEN-LAST:event_menuTorneioActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ConnectionFactory.getInstance().closeAll();
    }//GEN-LAST:event_formWindowClosing

    private void botaoTorneioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTorneioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoTorneioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FormularioPrincipal().setVisible(true);
                FormularioPrincipal formulario = new FormularioPrincipal();
                formulario.setLocationRelativeTo(null);
                formulario.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu botaoAjuda;
    private javax.swing.JMenu botaoCadastro;
    private javax.swing.JMenu botaoPrincipal;
    private javax.swing.JMenu botaoRelatorio;
    private javax.swing.JButton botaoTorneio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuJogador;
    private javax.swing.JMenuItem menuSobre;
    private javax.swing.JMenuItem menuTorneio;
    private javax.swing.JPanel painelGeral;
    // End of variables declaration//GEN-END:variables
}
